# .goreleaser.yaml

project_name: sift

# Run before the build
before:
  hooks:
    - go mod tidy

# Build configuration
builds:
  - id: sift
    main: ./cmd/sift/
    binary: sift
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# Archive configuration
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# Checksum configuration
checksum:
  name_template: "checksums.txt"

# Homebrew formula configuration
brews:
  - name: sift
    repository:
      owner: chriscorrea
      name: homebrew-sift
    homepage: "https://github.com/chriscorrea/sift"
    description: "Build LLM workflows on the command line"
    test: |
      system "#{bin}/sift --help"

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^style:"
      - "^chore:"
      - "^ci:"

# GitHub release configuration
release:
  github:
    owner: chriscorrea
    name: sift